version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  rabbitmq:
    image: rabbitmq:3.12.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: soatuser
      RABBITMQ_DEFAULT_PASS: soatpassword
      RABBITMQ_DEFAULT_VHOST: /
  ms-production:
    image: ghcr.io/postech-fiap-soat/ms-prodution:latest
    container_name: ms-production
    environment:
      ConnectionStrings_MongoConnection: "mongodb://root:root@my-mongodb:27017"
      RabbitMqConfig__Host: "rabbitmq"
      RabbitMqConfig__Port: "5672"
      RabbitMqConfig__User: "soatuser"
      RabbitMqConfig__Password: "soatpassword"
      RabbitMqConfig__VirtualHost: /
    ports:
      - "5100:80"
    depends_on:
      - mongodb
      - rabbitmq
