version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  ms-production:
    build: .
    container_name: ms-production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
